version: "3.4"

services:
  app:
    image: aguilas:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    user: "node"
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    ports:
      - "3000:3000"
    command: yarn run dev
